-- AlterTable
ALTER TABLE "User" ADD COLUMN "responseRate" DOUBLE PRECISION NOT NULL DEFAULT 0.75;

-- AlterTable
ALTER TABLE "Listing" ADD COLUMN "viewsCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Listing" ADD COLUMN "clicksCount" INTEGER NOT NULL DEFAULT 0;
